@baseUrl = http://localhost:4004

###
GET {{baseUrl}}/odata/v4/my/helloworld(input='World')


### service document
GET {{baseUrl}}/odata/v4/CatalogService

### metadata document
GET {{baseUrl}}/odata/v4/CatalogService/$metadata

### to get all employees
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet

### pagination - first parameter with ? next ones with &
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet?$top=2

### skip
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet?$top=2&$skip=2

### select only few fields - to reduce volume of data
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet?$select=nameFirst,nameLast,email

### where condition
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet?$filter=sex eq 'F'


### where condition pattern
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet?$filter=Contains(nameFirst,'ch')

### single employee
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet/02BD2137-0890-1EEA-A6C2-BB55C198A7FB

### single employee another syntax
GET {{baseUrl}}/odata/v4/CatalogService/EmployeeSet('02BD2137-0890-1EEA-A6C2-BB55C198A7FB')

### POST operation
POST {{baseUrl}}/odata/v4/CatalogService/EmployeeSet
Content-Type: application/json

{
  "nameFirst": "A R",
  "nameMiddle": null,
  "nameLast": "Rahman",
  "nameInitials": null,
  "sex": "M",
  "language": "E",
  "phoneNumber": null,
  "email": "arrahman@info",
  "loginName": "ARR",
  "currency_code": "USD",
  "salaryAmount": 1000000,
  "accountNumber": "76543219",
  "bankId": "66665555",
  "bankName": "My Bank of London"
}

### PATCH - Rememeber no comma after the last for valid json
PATCH  {{baseUrl}}/odata/v4/CatalogService/EmployeeSet/f5295c88-f1d3-4176-95c8-5a9846a3c37b
Content-Type: application/json

{
  "salaryAmount": 100000
}

### READ - newly created employee
GET  {{baseUrl}}/odata/v4/CatalogService/EmployeeSet/6403b3e4-e2b8-4c3d-952d-9ff5f2caf841


### DELETE - newly created employee
DELETE   {{baseUrl}}/odata/v4/CatalogService/EmployeeSet/6403b3e4-e2b8-4c3d-952d-9ff5f2caf841

### mixin with product view
GET  {{baseUrl}}/odata/v4/CatalogService/ProductViewSet

### to get item info - big list can try with single item to reduce load
GET  {{baseUrl}}/odata/v4/CatalogService/ProductViewSet?$expand=To_Items

###POs
GET  {{baseUrl}}/odata/v4/CatalogService/POs

###Single PO
GET  {{baseUrl}}/odata/v4/CatalogService/POs/02BD2137-0890-1EEA-A6C2-BB55C1978999

###Single PO
GET  {{baseUrl}}/odata/v4/CatalogService/POs/02BD2137-0890-1EEA-A6C2-BB55C1978999?$expand=items


### POST operation - DEEP Insert
POST {{baseUrl}}/odata/v4/CatalogService/POs
Content-Type: application/json

{
  "currency_code": "EUR",
  "gross_amount": 3913.91,
  "net_amount": 3289,
  "tax_amount": 624.91,
  "po_id": "300000000",
  "partner_guid_node_key": "74867AD200E41EDBA5D8B06885B04052",
  "lifecycle_status": "N",
  "overall_status": "P",
  "items": [
    {
      "currency_code": "ARS",
      "gross_amount": 154.7,
      "net_amount": 130,
      "tax_amount": 24.7,
      "po_item_pos": 10,
      "product_guid_node_key": "74867AD200E41EDBA5D8B06B26F60052"
    },
    {
      "currency_code": "ARS",
      "gross_amount": 402.22,
      "net_amount": 338,
      "tax_amount": 64.22,
      "po_item_pos": 20,
      "product_guid_node_key": "74867AD200E41EDBA5D8B06B26F06052"
    }

  ]
}